# Generated by Django 3.0.2 on 2020-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
