# Generated by Django 3.0.2 on 2020-05-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_category_is_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons'),
        ),
    ]
