# Generated by Django 3.0.2 on 2020-05-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0003_auto_20200502_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
    ]
