# Generated by Django 3.0.2 on 2020-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0004_remove_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='medium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='small',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='xlarge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
