# Generated by Django 3.0.2 on 2020-03-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('small', models.DecimalField(decimal_places=2, max_digits=20)),
                ('medium', models.DecimalField(decimal_places=2, max_digits=20)),
                ('large', models.DecimalField(decimal_places=2, max_digits=20)),
                ('xlarge', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('WHS', 'Whole Seller'), ('RET', 'Retail Seller'), ('BRK', 'Brick Maker')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.Distributor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.Region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
