# Generated by Django 3.0.2 on 2020-04-18 19:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='privileges',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Users.manage', 'Manage users'), ('Users.manage', 'Manage roles'), ('Setups.manage', 'Manage setups'), ('Customers.manage', 'Manage customers')], max_length=56, null=True),
        ),
    ]
