# Generated by Django 3.0.2 on 2020-04-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_supplier',
        ),
    ]
