# Generated by Django 3.0.2 on 2020-04-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_customer_is_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_records', to='tracking.Customer'),
        ),
    ]
