# Generated by Django 3.0.2 on 2020-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_record_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='trushed',
            field=models.BooleanField(default=False),
        ),
    ]
