# Generated by Django 3.0.2 on 2020-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20200620_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_alt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_alt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
