# Generated by Django 3.0.2 on 2020-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20200620_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
