# Generated by Django 3.0.2 on 2020-06-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20200620_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='fleet_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='description',
            name='machines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='description',
            name='outlets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='description',
            name='system',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='trucks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='description',
            name='types',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
