# Generated by Django 3.0.2 on 2020-06-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_auto_20200616_1848'),
        ('tracking', '0008_auto_20200620_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='setups.District'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='setups.Region'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='town',
            field=models.CharField(max_length=100),
        ),
    ]
