# Generated by Django 3.0.2 on 2020-10-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_auto_20200616_1848'),
        ('tracking', '0010_auto_20200622_2123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('name', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('brand', 'customer')},
        ),
    ]
