# Generated by Django 3.0.2 on 2020-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20201026_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='fleet_size',
            field=models.IntegerField(default=0),
        ),
    ]
